changelog:
  categories:
    - title: Core Changes
      labels:
        - '*'
    #   exclude:
    #     labels:
    #       - dependencies
    # - title: 👒 Dependencies
    #   labels:
    #     - dependencies
